language: python

python: "3.7"

install:
  - pip install -r requirements.txt

script:
  - pylint **/**.py #change this to run pylint on python files once we have some
  - pwd
  - cd/simulator
  - pytest
